using ApplicationCoreLibrary.Helpers;
using ApplicationCoreLibrary.Interfaces.Services;
using System.Diagnostics;
using Whois;

namespace ApplicationCoreLibrary.Services
{
    public class UrlAnalysisService : IUrlAnalysisService
    {
        public UrlAnalysis GenerateUrlAnalysis(string? url)
        {
            UrlAnalysis urlAnalysis = new UrlAnalysis();
            
            urlAnalysis.Url = url;
            ObtainUrlStatusAndDomain(urlAnalysis);
            LookupDomain(urlAnalysis); 
            
            return urlAnalysis;
        }

        public void ObtainUrlStatusAndDomain(UrlAnalysis urlAnalysis)
        {
            // 1) Create Process Info
            ProcessStartInfo psi = new ProcessStartInfo();
            psi.FileName = @"C:\Python311\python.exe";

            // 2) Provide arguments
            var scriptPath = @"C:\Users\Alex\Desktop\Diverse\GitHub\Repos\Bachelor-Thesis\bachelor-project-ai\inspect_web_page.py";
            psi.Arguments = $"{scriptPath} {urlAnalysis.Url}";

            // 3) Process configuration
            psi.UseShellExecute = false; // Do not use OS shell
            psi.CreateNoWindow = true; // We don't need new window
            psi.RedirectStandardOutput = true; // Any output, generated by application will be redirected back
            psi.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

            using (Process process = Process.Start(psi))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    var results = reader.ReadToEnd().Split('\n'); // Here is the result of StdOut(for example: print "test")
                    
                    Console.WriteLine("Errors:");
                    Console.WriteLine(stderr);
                    Console.WriteLine();

                    int extractedInfoIndex;
                    for (extractedInfoIndex = 0; extractedInfoIndex < results.Length; ++extractedInfoIndex)
                    {
                        if (results[extractedInfoIndex].Trim() == "Safe" || results[extractedInfoIndex].Trim() == "Suspicious")
                        {
                            break;
                        }
                    }
                    if (extractedInfoIndex == results.Length)
                    {
                        extractedInfoIndex = 0;
                    }
                    
                    urlAnalysis.Status = results[extractedInfoIndex].Trim();
                    urlAnalysis.Domain = results[extractedInfoIndex + 1].Trim();
                    if (urlAnalysis.Domain.Equals("None"))
                    {
                        urlAnalysis.Domain = null;
                    }
                }
            }
        }

        public void LookupDomain(UrlAnalysis urlAnalysis)
        {
            try
            {
                // Create a WhoisLookup instance
                var whois = new WhoisLookup();

                // Query domain
                var response = whois.Lookup(urlAnalysis.Domain);

                if (response.Registrar != null)
                {
                    urlAnalysis.RegistrarName = response.Registrar.Name;
                    urlAnalysis.RegistrarUrl = response.Registrar.Url;
                }
                if (response.Registered.ToString() == "" || response.Registered == null) 
                {
                    urlAnalysis.DomainCreationDate = null;
                }
                else
                {
                    urlAnalysis.DomainCreationDate = response.Registered.ToString();
                }
                if (response.Expiration.ToString() == "" || response.Expiration == null)
                {
                    urlAnalysis.DomainExpirationDate = null;
                }
                else
                {
                    urlAnalysis.DomainExpirationDate = response.Expiration.ToString();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }
    }
}
