﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MLModel_WebApi1
{
    public partial class MLModel
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"dots", @"dots"),new InputOutputColumnPair(@"http_status", @"http_status"),new InputOutputColumnPair(@"url_length", @"url_length"),new InputOutputColumnPair(@"at_symbol", @"at_symbol"),new InputOutputColumnPair(@"prefix_suffix", @"prefix_suffix"),new InputOutputColumnPair(@"ip_address", @"ip_address"),new InputOutputColumnPair(@"double_slash", @"double_slash"),new InputOutputColumnPair(@"short_serv", @"short_serv"),new InputOutputColumnPair(@"domain_status", @"domain_status"),new InputOutputColumnPair(@"domain_age", @"domain_age"),new InputOutputColumnPair(@"domain_reg", @"domain_reg"),new InputOutputColumnPair(@"report", @"report"),new InputOutputColumnPair(@"hyperlinks", @"hyperlinks"),new InputOutputColumnPair(@"a_rate", @"a_rate"),new InputOutputColumnPair(@"img_rate", @"img_rate"),new InputOutputColumnPair(@"link_rate", @"link_rate"),new InputOutputColumnPair(@"script_rate", @"script_rate"),new InputOutputColumnPair(@"a_without_href_rate", @"a_without_href_rate"),new InputOutputColumnPair(@"empty_hyp_rate", @"empty_hyp_rate"),new InputOutputColumnPair(@"int_hyp_rate", @"int_hyp_rate"),new InputOutputColumnPair(@"ext_hyp_rate", @"ext_hyp_rate"),new InputOutputColumnPair(@"ext_int_hyp_rate", @"ext_int_hyp_rate"),new InputOutputColumnPair(@"forms", @"forms"),new InputOutputColumnPair(@"sus_forms", @"sus_forms"),new InputOutputColumnPair(@"redirects", @"redirects"),new InputOutputColumnPair(@"request_url", @"request_url"),new InputOutputColumnPair(@"sus_anchors", @"sus_anchors"),new InputOutputColumnPair(@"links_in_tags", @"links_in_tags"),new InputOutputColumnPair(@"email_in_forms", @"email_in_forms"),new InputOutputColumnPair(@"sfh", @"sfh"),new InputOutputColumnPair(@"iframe", @"iframe"),new InputOutputColumnPair(@"favicon", @"favicon")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"dots",@"http_status",@"url_length",@"at_symbol",@"prefix_suffix",@"ip_address",@"double_slash",@"short_serv",@"domain_status",@"domain_age",@"domain_reg",@"report",@"hyperlinks",@"a_rate",@"img_rate",@"link_rate",@"script_rate",@"a_without_href_rate",@"empty_hyp_rate",@"int_hyp_rate",@"ext_hyp_rate",@"ext_int_hyp_rate",@"forms",@"sus_forms",@"redirects",@"request_url",@"sus_anchors",@"links_in_tags",@"email_in_forms",@"sfh",@"iframe",@"favicon"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"label",inputColumnName:@"label"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LightGbm(new LightGbmMulticlassTrainer.Options(){NumberOfLeaves=47,NumberOfIterations=12,MinimumExampleCountPerLeaf=38,LearningRate=0.999999776672986,LabelColumnName=@"label",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=7.12629688134076E-05,FeatureFraction=0.78183278647473,L1Regularization=3.99434385661449E-09,L2Regularization=0.999999776672986},MaximumBinCountPerFeature=453}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
