// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel_WebApi1
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"dots")]
            public float Dots { get; set; }

            [ColumnName(@"http_status")]
            public float Http_status { get; set; }

            [ColumnName(@"url_length")]
            public float Url_length { get; set; }

            [ColumnName(@"at_symbol")]
            public float At_symbol { get; set; }

            [ColumnName(@"prefix_suffix")]
            public float Prefix_suffix { get; set; }

            [ColumnName(@"ip_address")]
            public float Ip_address { get; set; }

            [ColumnName(@"double_slash")]
            public float Double_slash { get; set; }

            [ColumnName(@"short_serv")]
            public float Short_serv { get; set; }

            [ColumnName(@"domain_status")]
            public float Domain_status { get; set; }

            [ColumnName(@"domain_age")]
            public float Domain_age { get; set; }

            [ColumnName(@"domain_reg")]
            public float Domain_reg { get; set; }

            [ColumnName(@"report")]
            public float Report { get; set; }

            [ColumnName(@"hyperlinks")]
            public float Hyperlinks { get; set; }

            [ColumnName(@"a_rate")]
            public float A_rate { get; set; }

            [ColumnName(@"img_rate")]
            public float Img_rate { get; set; }

            [ColumnName(@"link_rate")]
            public float Link_rate { get; set; }

            [ColumnName(@"script_rate")]
            public float Script_rate { get; set; }

            [ColumnName(@"a_without_href_rate")]
            public float A_without_href_rate { get; set; }

            [ColumnName(@"empty_hyp_rate")]
            public float Empty_hyp_rate { get; set; }

            [ColumnName(@"int_hyp_rate")]
            public float Int_hyp_rate { get; set; }

            [ColumnName(@"ext_hyp_rate")]
            public float Ext_hyp_rate { get; set; }

            [ColumnName(@"ext_int_hyp_rate")]
            public float Ext_int_hyp_rate { get; set; }

            [ColumnName(@"forms")]
            public float Forms { get; set; }

            [ColumnName(@"sus_forms")]
            public float Sus_forms { get; set; }

            [ColumnName(@"redirects")]
            public float Redirects { get; set; }

            [ColumnName(@"request_url")]
            public float Request_url { get; set; }

            [ColumnName(@"sus_anchors")]
            public float Sus_anchors { get; set; }

            [ColumnName(@"links_in_tags")]
            public float Links_in_tags { get; set; }

            [ColumnName(@"email_in_forms")]
            public float Email_in_forms { get; set; }

            [ColumnName(@"sfh")]
            public float Sfh { get; set; }

            [ColumnName(@"iframe")]
            public float Iframe { get; set; }

            [ColumnName(@"favicon")]
            public float Favicon { get; set; }

            [ColumnName(@"label")]
            public float Label { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"dots")]
            public float Dots { get; set; }

            [ColumnName(@"http_status")]
            public float Http_status { get; set; }

            [ColumnName(@"url_length")]
            public float Url_length { get; set; }

            [ColumnName(@"at_symbol")]
            public float At_symbol { get; set; }

            [ColumnName(@"prefix_suffix")]
            public float Prefix_suffix { get; set; }

            [ColumnName(@"ip_address")]
            public float Ip_address { get; set; }

            [ColumnName(@"double_slash")]
            public float Double_slash { get; set; }

            [ColumnName(@"short_serv")]
            public float Short_serv { get; set; }

            [ColumnName(@"domain_status")]
            public float Domain_status { get; set; }

            [ColumnName(@"domain_age")]
            public float Domain_age { get; set; }

            [ColumnName(@"domain_reg")]
            public float Domain_reg { get; set; }

            [ColumnName(@"report")]
            public float Report { get; set; }

            [ColumnName(@"hyperlinks")]
            public float Hyperlinks { get; set; }

            [ColumnName(@"a_rate")]
            public float A_rate { get; set; }

            [ColumnName(@"img_rate")]
            public float Img_rate { get; set; }

            [ColumnName(@"link_rate")]
            public float Link_rate { get; set; }

            [ColumnName(@"script_rate")]
            public float Script_rate { get; set; }

            [ColumnName(@"a_without_href_rate")]
            public float A_without_href_rate { get; set; }

            [ColumnName(@"empty_hyp_rate")]
            public float Empty_hyp_rate { get; set; }

            [ColumnName(@"int_hyp_rate")]
            public float Int_hyp_rate { get; set; }

            [ColumnName(@"ext_hyp_rate")]
            public float Ext_hyp_rate { get; set; }

            [ColumnName(@"ext_int_hyp_rate")]
            public float Ext_int_hyp_rate { get; set; }

            [ColumnName(@"forms")]
            public float Forms { get; set; }

            [ColumnName(@"sus_forms")]
            public float Sus_forms { get; set; }

            [ColumnName(@"redirects")]
            public float Redirects { get; set; }

            [ColumnName(@"request_url")]
            public float Request_url { get; set; }

            [ColumnName(@"sus_anchors")]
            public float Sus_anchors { get; set; }

            [ColumnName(@"links_in_tags")]
            public float Links_in_tags { get; set; }

            [ColumnName(@"email_in_forms")]
            public float Email_in_forms { get; set; }

            [ColumnName(@"sfh")]
            public float Sfh { get; set; }

            [ColumnName(@"iframe")]
            public float Iframe { get; set; }

            [ColumnName(@"favicon")]
            public float Favicon { get; set; }

            [ColumnName(@"label")]
            public uint Label { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
